### ISSUE TITLE
Wildcards shouldn't be sorted

### ISSUE THREAD

**Issue by kamyker** [adieyal/dynamicprompts#79] opened 2023-04-15 13:59 UTC
I thought wildcards would work the same way normal text does but they don't for combinatorial mode.

When generating something like "{new|dusty|broken} car" order is preserved but when these value are in wildcard:
```
new
dusty
broken
```
They will be sorted and output will be in wrong order (broken, dusty, new).

**Comment by adieyal** [comment] 2023-05-26 19:33
@akx this is intended behaviour rather than a bug. I agree that this should be an option though. Similarly, we should probably have an option to not de-duplicate. That would be a quick and dirty way to support weights in wildcard files. I would leave it off by default for backwards compatibility.

**Comment by akx** [comment] 2023-05-26 20:19
@adieyal 🤔 Do we actually have a good reason to dedupe or sort wildcard contents other than it feels like the clean and nice thing to do?

**Comment by adieyal** [comment] 2023-05-26 20:28
i think that originally it was a way to handle situations where you might have duplicated wildcards across multiple files. I'm not convinced it makes sense anymore, but probably best to keep it as default behaviour in case users rely on it.

**Comment by kamyker** [comment] 2023-05-27 11:02
Seems like a bug to me for combinatorial mode as even example in readme wouldn't produce the same result:

> My favourite season is __seasons__
> will produce:
> My favourite season is Summer
> My favourite season is August
> My favourite season is Winter
> My favourite season is Sprint

I'd guess far more users will face this issue than amount of users relying on deduping.

**Comment by adieyal** [comment] 2023-05-27 11:32
It was a decision made in the early days of the extension based on user requests. I have just pushed a PR that allows the user to disable this. Once it's merged into dynamicprompts, I will add configuration options to the extension

**Comment by kamyker** [comment] 2023-05-27 20:37
Cool, thanks!

**Comment by akx** [comment] 2023-07-17 09:58
#27 has been merged, so closing this on this side.

**Closed by akx** 2023-07-17 09:58 UTC
Labels: bug
